AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB tables for Compass AI UX Intake

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Resources:
  IntakesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'compass-ai-intakes-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: submittedAt
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: status-submittedAt-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: submittedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Application
          Value: CompassAI

  DraftsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'compass-ai-drafts-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Application
          Value: CompassAI

  AuditLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'compass-ai-audit-log-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      Tags:
        - Key: Application
          Value: CompassAI

Outputs:
  IntakesTableName:
    Value: !Ref IntakesTable
  DraftsTableName:
    Value: !Ref DraftsTable
  AuditLogTableName:
    Value: !Ref AuditLogTable
